### ISSUE TITLE
Command for reading status of heating on/off

### ISSUE THREAD

**Issue by Deez73** [dkjonas/Wavin-AHC-9000-mqtt#8]
Is it possible to manually add a command/syntax to get the state of the floor heating actually heating or not?

Auto discovery doesn't work for me, so I manually configured the sensors (working fine), but not for the status on floor heating or not.

Using this syntax right now, but lacking heating status:
```
    current_temperature_topic: "heat/floorXXXXXXXXXXXX/0/current"
    temperature_command_topic: "heat/floorXXXXXXXXXXXX/0/target_set"
    temperature_state_topic: "heat/floorXXXXXXXXXXXX/0/target"
```

**Comment by dkjonas** [comment]
You can create extra sensors to monitor the `heat/floorXXXXXXXXXXXX/n/output` topic. Something like (untested):

```
binary_sensor:
  - platform: mqtt
    name: "Output of channel 0"
    state_topic: "heat/floorXXXXXXXXXXXX/0/output"
    payload_on: "on"
    payload_off: "off"
    availability_topic: "heat/floorXXXXXXXXXXXX/online"
    payload_available: "True"
    payload_not_available: "False"
```
You can change if the heat is enabled or not using `heat/floorXXXXXXXXXXXX/0/mode`
